.TH "c_handler_list" 3 "Quarta, 25 de Janeiro de 2012" "servw" \" -*- nroff -*-
.ad l
.nh
.SH NAME
c_handler_list \- 
.SH SYNOPSIS
.br
.PP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "int \fBcurrent\fP"
.br
.RI "\fIQuantos handlers estao servindo clientes agora'\&. \fP"
.ti -1c
.RI "int \fBmax\fP"
.br
.RI "\fIMaximo de handlers possiveis ao mesmo tempo'\&. \fP"
.ti -1c
.RI "struct c_handler * \fBbegin\fP"
.br
.RI "\fIPrimeiro handler na lista'\&. \fP"
.ti -1c
.RI "struct c_handler * \fBend\fP"
.br
.RI "\fIUltimo handler na lista'\&. \fP"
.in -1c

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para servw a partir de seu código-fonte'\&.
