.TH "headers_t" 3 "Quarta, 25 de Janeiro de 2012" "servw" \" -*- nroff -*-
.ad l
.nh
.SH NAME
headers_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "char * \fBmethod\fP"
.br
.ti -1c
.RI "char * \fBpath\fP"
.br
.ti -1c
.RI "char * \fBhttp_version\fP"
.br
.ti -1c
.RI "char * \fBhost\fP"
.br
.ti -1c
.RI "char * \fBuser_agent\fP"
.br
.ti -1c
.RI "char * \fBstatus\fP"
.br
.ti -1c
.RI "char * \fBcontent_length\fP"
.br
.ti -1c
.RI "char * \fBcontent_type\fP"
.br
.ti -1c
.RI "char * \fBlast_modified\fP"
.br
.ti -1c
.RI "char * \fBserver\fP"
.br
.in -1c

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para servw a partir de seu código-fonte'\&.
