.TH "httpparser_t" 3 "Quarta, 25 de Janeiro de 2012" "servw" \" -*- nroff -*-
.ad l
.nh
.SH NAME
httpparser_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "char \fBmessage\fP [BUFFER_SIZE]"
.br
.ti -1c
.RI "struct \fBheaders_t\fP \fBheader\fP"
.br
.in -1c

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para servw a partir de seu código-fonte'\&.
