.TH "src/http.h" 3 "Quarta, 25 de Janeiro de 2012" "servw" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/http.h \- 
.PP
Definicao dos procedimentos relacionados a parsear HTTP'\&.  

.SH SYNOPSIS
.br
.PP
.SS "Enumerações"

.in +1c
.ti -1c
.RI "enum \fBstatus_codes\fP { \fBNONE\fP =  -1, \fBOK\fP =  200, \fBBAD_REQUEST\fP =  400, \fBFORBIDDEN\fP =  403, \fBNOT_FOUND\fP =  404, \fBSERVER_ERROR\fP =  500 }"
.br
.RI "\fIOs status codes HTTP'\&. \fP"
.in -1c
.SH "Descrição Detalhada"
.PP 
Definicao dos procedimentos relacionados a parsear HTTP'\&. 


.SH "Enumerações"
.PP 
.SS "enum \fBstatus_codes\fP"
.PP
Os status codes HTTP'\&. 1xx - Informational Message 2xx - Success 3xx - Redirection 4xx - Client Error 5xx - Server Error 
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para servw a partir de seu código-fonte'\&.
