.TH "todo" 3 "Quarta, 25 de Janeiro de 2012" "servw" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Lista de Futuras Atividades 
.IP "\fBGlobal \fBbuild_header\fP (struct \fBclienthandler_t\fP *h)\fP" 1c
Remover valores arbitrarios dos buffers'\&.  
.IP "\fBGlobal \fBbuild_header\fP (char *buf, size_t bufsize, int status, char *status_msg char *cont_type, off_t cont_length, char *last_modif)\fP" 1c
Remover valores arbitrarios dos buffers'\&.  
.IP "\fBGlobal \fBget_status_msg\fP (int status, char *buf, size_t bufsize)\fP" 1c
adicionar suporte a mais mensagens de erro!  
.IP "\fBArquivo \fBhttp'\&.c\fP \fP" 1c
Tornar o parser mais generalizado'\&. (MUITO TRABALHO)  
.IP "\fBGlobal \fBmain\fP (int argc, char *argv[])\fP" 1c
.IP "\fBGlobal \fBparse_request\fP (struct \fBclienthandler_t\fP *h)\fP" 1c
Por enquanto so mexemos com filename'\&. Implementar metodo e versao  
.IP "\fBGlobal \fBsocket_set_nonblocking\fP (int sck)\fP" 1c
Entender o que esses operadores bitwise fazem'\&. 
.PP

